### ISSUE TITLE
MacOS not working with latest changes in master

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#79]
Screen is just black on mac but on linux gl2/3 works ok.

**Comment by elect86** [comment]
Can you try on mac d60ba95a193867bd0f61a9ff1e0663b4ae98f151 and 37242187eac5fe5c3c08ee39e77b1f6824134c4a

**Comment by yuraj11** [comment]
For some reason I can not make JAR from d60ba95. I am getting errors like Unresolved reference: BufferTarget, Usage, usingProgram etc.

**Comment by yuraj11** [comment]
I can not compile d60ba95 while 3724218 can be compiled:
```
 ./gradlew lightjar
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (9, 19): Unresolved reference: BufferTarget
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (10, 19): Unresolved reference: Usage
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (20, 20): Unresolved reference: usingProgram
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (21, 20): Unresolved reference: initTexture2d
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (51, 39): None of the following functions can be called with the arguments supplied: 
public final fun createFromSource(type: ShaderType, sourceText: Array<String>): GlShader defined in gln.objects.GlShader.Companion
public final fun createFromSource(type: ShaderType, sourceText: String): GlShader defined in gln.objects.GlShader.Companion
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (52, 39): None of the following functions can be called with the arguments supplied: 
public final fun createFromSource(type: ShaderType, sourceText: Array<String>): GlShader defined in gln.objects.GlShader.Companion
public final fun createFromSource(type: ShaderType, sourceText: String): GlShader defined in gln.objects.GlShader.Companion
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (64, 9): Unresolved reference: usingProgram
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (65, 27): Unresolved reference: uniform
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (66, 23): Unresolved reference: unit
e: /home/yuraj/IdeaProjects/imgui/src/main/kotlin/imgui/impl/ImplGL2.kt: (72, 9): None of the following functions can be called with the arguments supplied: 
public inline fun glBufferData(target: BufferTarget, mat: Mat4, usage: Usage): Unit defined in gln.buffer

```

**Comment by elect86** [comment]
that's the 
[d60ba95](https://github.com/kotlin-graphics/imgui/commit/d60ba95a193867bd0f61a9ff1e0663b4ae98f151) output?

**Comment by yuraj11** [comment]
Yes - just checkout on that commit and then compile the imgui project using `./gradlew lightjar`

**Comment by elect86** [comment]
Oh yeah, it's broken, what about the next where I fixed the errors?

**Comment by Sylvyrfysh** [comment]
out of curiosity, which mac are you running this on?

**Comment by yuraj11** [comment]
Mojave version 10.14.3

**Comment by yuraj11** [comment]
3724218 crashes on:
```
Caused by: java.lang.NoSuchMethodError: gln.objects.GlTexture.constructor-impl$default(IILkotlin/jvm/internal/DefaultConstructorMarker;)V
    at imgui.impl.ImplGL2.<init>(ImplGL2.kt:36)
    at imgui.impl.LwjglGlfw.<init>(LwjglGlfw.kt:148)
    at imgui.impl.LwjglGlfw$Companion.init(LwjglGlfw.kt:31)
    at imgui.impl.LwjglGlfw$Companion.init$default(LwjglGlfw.kt:30)
```

**Comment by elect86** [comment]
something is wrong with the gln dependency

how do you import imgui into your project? Can you run `dependencies`?

gln shall be 7e921b01cc01dbf3444e320f2a2af04490158952

**Comment by yuraj11** [comment]
```
compile 'com.github.kotlin-graphics:uno-sdk:60edf33067835253aa30ac79bd5129363fee953f'
compile files("../libs/imgui-light.jar")

gradle
       configurations.compile.resolvedConfiguration.getResolvedArtifacts().forEach {
            if (it.moduleVersion.id.group == "org.lwjgl" && it.moduleVersion.id.name != "lwjgl-jawt" && it.moduleVersion.id.name != "lwjgl-vulkan") {
                runtime "org.lwjgl:${it.moduleVersion.id.name}:${it.moduleVersion.id.version}:${lwjglNatives}"
            }
        }
```

**Comment by elect86** [comment]
what's the output of `dependencies`? In Idea under Gradle Tasks `help`

**Comment by yuraj11** [comment]
In my project:
```
\--- com.github.kotlin-graphics:uno-sdk:60edf33067835253aa30ac79bd5129363fee953f
     +--- com.github.kotlin-graphics:gln:7e921b01cc01dbf3444e320f2a2af04490158952
     |    +--- com.github.kotlin-graphics:gli:968eb79758bf3475e8cf1a93f138b2a19aadd7a5
     |    |    +--- com.github.kotlin-graphics.glm:glm:a1cafbd4e1bda500291b19a8d0cb75374f97688c
     |    |    |    +--- com.github.kotlin-graphics:kotlin-unsigned:0e3cc3ec155986f2100fee03cc143cbd3dfd0d84
     |    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    |    |    +--- com.github.kotlin-graphics:kool:7c3dfaf417b00a0b7fe5dd273bf10291ebfe45d0
     |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    |    |    |    +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     |    |    |    |    \--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    |    |    +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     |    |    |    +--- org.lwjgl:lwjgl-glfw:3.2.2-SNAPSHOT (*)
     |    |    |    +--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     |    |    |    +--- org.lwjgl:lwjgl-openal:3.2.2-SNAPSHOT (*)
     |    |    |    +--- org.lwjgl:lwjgl-opengl:3.2.2-SNAPSHOT (*)
     |    |    |    \--- org.lwjgl:lwjgl-stb:3.2.2-SNAPSHOT (*)
     |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    |    +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     |    |    +--- org.lwjgl:lwjgl-glfw:3.2.2-SNAPSHOT (*)
     |    |    +--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     |    |    +--- org.lwjgl:lwjgl-openal:3.2.2-SNAPSHOT (*)
     |    |    +--- org.lwjgl:lwjgl-opengl:3.2.2-SNAPSHOT (*)
     |    |    \--- org.lwjgl:lwjgl-stb:3.2.2-SNAPSHOT (*)
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.21
     |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     |    +--- org.lwjgl:lwjgl-glfw:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-openal:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-opengl:3.2.2-SNAPSHOT (*)
     |    \--- org.lwjgl:lwjgl-stb:3.2.2-SNAPSHOT (*)
     +--- com.github.kotlin-graphics:vkk:a593ed45c49422b19e74b165a97bcd4a1245e2fd
     |    +--- com.github.kotlin-graphics:gli:968eb79758bf3475e8cf1a93f138b2a19aadd7a5 (*)
     |    +--- graphics.scenery:spirvcrossj:0.5.0-1.1.85
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.21 (*)
     |    +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     |    +--- org.lwjgl:lwjgl-glfw:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-openal:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-opengl:3.2.2-SNAPSHOT (*)
     |    +--- org.lwjgl:lwjgl-stb:3.2.2-SNAPSHOT (*)
     |    \--- org.lwjgl:lwjgl-vulkan:3.2.2-SNAPSHOT
     |         \--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     +--- org.jetbrains.kotlin:kotlin-reflect:1.3.21 (*)
     +--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT
     +--- org.lwjgl:lwjgl-glfw:3.2.2-SNAPSHOT (*)
     +--- org.lwjgl:lwjgl-jemalloc:3.2.2-SNAPSHOT (*)
     +--- org.lwjgl:lwjgl-openal:3.2.2-SNAPSHOT (*)
     +--- org.lwjgl:lwjgl-opengl:3.2.2-SNAPSHOT (*)
     +--- org.lwjgl:lwjgl-stb:3.2.2-SNAPSHOT (*)
     +--- org.lwjgl:lwjgl-vulkan:3.2.2-SNAPSHOT (*)
     \--- org.lwjgl:lwjgl-jawt:3.2.2-SNAPSHOT
          \--- org.lwjgl:lwjgl:3.2.2-SNAPSHOT

```

**Comment by elect86** [comment]
gln version matches.. I dont know what else to do

and what about if you try the actual last snapshot?

**Comment by yuraj11** [comment]
With the same process but with latest master changes It works (With the mentioned black screen on mac but at least It runs) dependency tree is same.

**Comment by Sylvyrfysh** [comment]
Try branch TestLowGLN commit a0e6c1bf. The reason I ask which Mac is that it is clear that we'll need to test on more than just windows and linux systems in the future , so I figure getting an older mac laptop only doing GL21 isn't a bad idea

**Comment by yuraj11** [comment]
673d347 still black screen

**Comment by Sylvyrfysh** [comment]
Do you run your git and gradle in the same shell? if so, can you send what you'd do to check out and build your jars?

**Comment by yuraj11** [comment]
But I tested 673d347 and It didn't work - I mean I could compile It and run but I still see black screen on Mac only.

**Comment by Sylvyrfysh** [comment]
Does TestLowGLN 3724218 work?

**Comment by yuraj11** [comment]
Crashes when I try to run screen with imgui (tested on linux):
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: gln.vertexArray.GlVertexArray.constructor-impl$default(IILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.x.prototype.desktop.DesktopLauncher.main(DesktopLauncher.kt:19)
Caused by: java.lang.NoSuchMethodError: gln.vertexArray.GlVertexArray.constructor-impl$default(IILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at imgui.impl.ImplGL3.<init>(ImplGL3.kt:53)
	at imgui.impl.LwjglGlfw.<init>(LwjglGlfw.kt:146)
	at imgui.impl.LwjglGlfw$Companion.init(LwjglGlfw.kt:31)
	at imgui.impl.LwjglGlfw$Companion.init$default(LwjglGlfw.kt:30)
```

I have tried It with imgui.jar `compile files("../libs/imgui.jar")`
Also while I am using fat jar instead of imgui-light jar I see this warning:
```
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.

```

**Comment by Sylvyrfysh** [comment]
Can you refresh dependencies?

In IntelliJ this is done by clicking on the gradle window, clicking on the elephant at top, and then typing `--refresh-dependencies` in the window. Then run. This should fix that problem.

Do you have auto-import turned on? That could fix this issue in the future

**Comment by yuraj11** [comment]
Hm still doesn't work. Could you please upload Jar for  3724218 ?

**Comment by Sylvyrfysh** [comment]
All jars uploaded to [my website](https://shared.nicholaspjohnson.com/imgui/)

**Comment by yuraj11** [comment]
https://shared.nicholaspjohnson.com/imgui/master/-LATEST/imgui-light.jar - black screen on mac, OK on linux

**Comment by Sylvyrfysh** [comment]
Does v1.68.01-00 work? I'm buying an old macbook soon so I'll be able to test, but until then it's a shot in the dark

**Comment by yuraj11** [comment]
Still the same problem as in https://github.com/kotlin-graphics/imgui/issues/79#issuecomment-471561952 - here you can test It:
[guitest.zip](https://github.com/kotlin-graphics/imgui/files/3013760/guitest.zip)

**Comment by Sylvyrfysh** [comment]
[This](https://shared.nicholaspjohnson.com/imgui/master/v1.68.01-00_LWJGL_UP/) should fix the LWJGL version mismatch

**Comment by yuraj11** [comment]
Now It runs on linux and mac but I still see black screen on Mac.

**Comment by elect86** [comment]
@yuraj11 , I lost myelft, just to sum up, did the gl2 on mac ever worked? 

If yes, let's take that and restore it for the moment, then maybe we can step by step apply all the changes in order to isolate the bug

**Comment by yuraj11** [comment]
Last working version on Mac for me is a8b471dc252e9067770792492bbed9aa451bf834 . On later versions I see only black screen on Mac.

**Comment by Sylvyrfysh** [comment]
My guess is that it's got to do with the framebuffer scaling change. If I put together s debug build, will you run it?

**Comment by elect86** [comment]
I got some time in the meanwhile and I'd like gln to be working asap

Give it a try, 7b47b533dba04a13870e39e9281d63ca655fbba7 (branch `#79`)

**Comment by yuraj11** [comment]
#79
```
Exception in thread "main" java.lang.IllegalStateException: Property textureName should be initialized before get.
	at kotlin.properties.NotNullVar.getValue(Delegates.kt:62)
	at gln.texture.TextureKt.getTextureName(texture.kt)
	at imgui.impl.ImplGL2.createFontsTexture(ImplGL2.kt:103)
	at imgui.impl.ImplGL2.createDeviceObjects(ImplGL2.kt:80)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:159)
	at imgui.impl.LwjglGlfw$Companion.newFrame(LwjglGlfw.kt:34)
```
OpenGL2 crashes even on linux for me. OpenGL3 does not crash on linux. So no reason to test It on Mac where is opengl2.

**Comment by elect86** [comment]
Sorry, `textureName` refers to a global variable that has nothing to do in this context

1591dcc5212eae7e21a1edbadedc382899f4302b

**Comment by yuraj11** [comment]
@elect86 this one works correctly and also no more black screen on mac :+1:

**Comment by yuraj11** [comment]
[crash.txt](https://github.com/kotlin-graphics/imgui/files/3067323/crash.txt)
but this crash still randomly happens on MAC OpenGL2

**Comment by elect86** [comment]
how much random does it crash?

**Comment by yuraj11** [comment]
Not so often maybe about 3 times in 8 hours while working on the project.

**Comment by Sylvyrfysh** [comment]
When does the crash happen? It's deep in GLFW code

**Comment by yuraj11** [comment]
Totally random :)

**Comment by elect86** [comment]
The crash points deep inside glfw, weird stuff, menu and menu key event

Spasi suggested that it may be not random, maybe the user does something odd that triggers it

However, I'm gonna open probably an issue on glfw 

One last thing, did you happen to notice the same random crashes with the working snapshot before this last one? If you had a chance to test it intensively as it looks you did now

**Comment by elect86** [comment]
Hey Juraj,

could you try to build lwjgl on mac with glfw in debug mode ([this](https://github.com/LWJGL-CI/glfw/blob/master-macosx/.travis.yml) without the AWS stuff and `CMAKE_BUILD_TYPE` to debug)

**Comment by elect86** [comment]
https://github.com/glfw/glfw/issues/1467#issuecomment-486670700

**Comment by yuraj11** [comment]
Sorry I will investigate It later when I will have more time to do It. But in the meantime could you please merge It to master 1591dcc ?

**Comment by yuraj11** [comment]
And yes I had crashes on mac always with imgui as mentioned in previous issues.

**Comment by elect86** [comment]
Sure, pushed

**Comment by elect86** [comment]
Hey Jura, any news?

**Comment by yuraj11** [comment]
Hi, sorry I am not using imgui anymore - I have migrated to libgdx scene2d. Anyway thanks for your effort.

**Comment by elect86** [comment]
If anyone has having problems with mac and GL2, he can feel free to reopen
